### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by EddyMI3d** [kanocz/octopi_eta_override#1]
Hi! Nice work. 
But I'm a bit confused. I already have this one installed: 
https://plugins.octoprint.org/plugins/m73etaoverride/   
https://github.com/sysadminsh/OctoPrint-M73ETAOverride .

Does your plugin do something different?

**Comment by kanocz** [comment]
@EddyMI3d Hi, thank you
yes, M73Override works if you're printing from octoprint, but this one is suitable when you're printing from SDcard and you don't know about M73 as octoprint doesn't know about content of gcode file

**Comment by EddyMI3d** [comment]
Ok, I see. That makes sense!  :thumbs:
