### ISSUE TITLE
Mismatch between time and percentage progress

### ISSUE THREAD

**Issue by ge123** [kanocz/octopi_eta_override#10]
The ETA time seems accurate, but the percentage progress bar still lags the display on the Prusa.

**Comment by kanocz** [comment]
@ge123 yes, this plugin only overrides ETA (remaining time), but not percentage... as for me only remaining time is important to know remotely :)

**Comment by arekm** [comment]
Octoprint currently doesn't even have API for that.

There are some ways but that's messing with internals (which can change anytime) like this plugin does: https://github.com/celogeek/OctoPrint-ProgressBasedOnTime
and these tries end up badly and cause other problems (https://github.com/celogeek/OctoPrint-ProgressBasedOnTime/issues/1)

**Comment by arekm** [comment]
So solved by https://github.com/kanocz/octopi_eta_override/pull/15
