### ISSUE TITLE
Feature request: add current time to 'time left' to make wall-clock ETA

### ISSUE THREAD

**Issue by Mrten** [kanocz/octopi_eta_override#11]
If you'd add the current time to 'time left', you could see whether the ETA shifts backwards.

I sometimes set the print speed multiplier to 200%, but that makes both 'print time left' and the value on the display of the printer inaccurate. If the exact ETA you could see how much :)

**Comment by kanocz** [comment]
@Mrten I'm just converting value which is reported by firmware... so speed multiplier question is on firmware (Marlin) developers :)

**Comment by Mrten** [comment]
I gave the wrong example, sorry, let me give another:

The print I'm running at this moment says, in octoprint:
```
Print Time Left: 3 hours ●
```
(02:48:17 when you hover)
I'm suggesting

```
Print Time Left: 3 hours (18:10) ●
```
18:10 is calculated by taking the current time, 15:22, plus 2:48.

Now I know instantly when the print will be done.
