### ISSUE TITLE
Octoprint upgrade to 0.2.0 doesn't upgrade

### ISSUE THREAD

**Issue by ctgreybeard** [kanocz/octopi_eta_override#14]
I received a notice that version 0.2.0 was available (from 0.1.1) but when I went to install the upgrade it reinstalled 0.1.1. I removed the plugin and installed from Plugi Manager but 0.1.1 installed also.

**Comment by Artain** [comment]
setup.py still has version 0.1.1 listed. The installation seems to be working but after the successful install the new version check checks again against version 0.1.1

**Comment by kanocz** [comment]
sorry, forget about this :( 
fixed as 0.2.1
please test (I have no Průša printer anymore...)

**Comment by Artain** [comment]
Seems to be working. Thanks.

**Comment by ctgreybeard** [comment]
0.2.1 installed OK and appears to work fine. I did not check it against Stealth Mode, though.

Thanks for the quick update!
