### ISSUE TITLE
Prusa MK2.5S compatibility?

### ISSUE THREAD

**Issue by toto99303** [kanocz/octopi_eta_override#2]
Hello, many thanks for this plugin. I'm trying to make it work with my MK2.5S, but the ETA is still the one that octoprint predicts, very wrong. I can see terminal returns this:

Send: M27
Recv: NORMAL MODE: Percent done: 2; print time remaining in mins: 299
Recv: SILENT MODE: Percent done: 255; print time remaining in mins: -1
Recv: Octomon_LoLin_0.2mm_PLA_MK2.5S_5h7m.gcode
Recv: SD printing byte 44852/6972251
Recv: 00:09
Recv: ok

So it should be working, right? What could be wrong?

**Comment by kanocz** [comment]
As for me it have to work because message is the same as I have on MK3 and fits to regular expression used in this extension. Do you have logs from your octoprint? maybe it's some problem with plugin itself? (for example incompatibles in python version or something like this?)

**Comment by toto99303** [comment]
It turns out the time is read fine, Printoid shows it correctly, only on the octoprint page it shows it strange. For example 3.5h left and when you hover the cursor it shows the real time left. Have a look:
![time_octo](https://user-images.githubusercontent.com/20519170/77108207-7ad26180-6a2a-11ea-8443-16107811fc3d.PNG)

**Comment by kanocz** [comment]
@toto99303 it's just octoprint's style of displaying time :( I think it's an option change it somewhere in settings, but anyway it's not about my plugin, so I'm closing issue... but thank you for using it :)

**Comment by arekm** [comment]
"Appearance" and disable "Show fuzzy print time estimates" for anyone who ends up reading this issue.
