### ISSUE TITLE
Allow for choice between normal and silent mode ETAs

### ISSUE THREAD

**Issue by Mushroom** [kanocz/octopi_eta_override#4]
Hello,

I find this plugin extremely useful, but I always find the estimates are a few minutes out, as I run the printer in silent mode. Is it possible to add a configuration menu option to choose between parsing the "NORMAL" and "SILENT" lines?

Thanks

**Comment by kanocz** [comment]
in general I see that it's only few percents difference in time, but allowing to switch will require configuration page and so on which will take more time that plugin itself taken :( maybe I'll do this in future, but I have very little motivation - it work good enough for me )

**Comment by hergtoler** [comment]
You can use this pull request, and it will work for silent mode:
#6 

If you also use custom firmware, it will automatically change between silent and normal:
https://github.com/hergtoler/Prusa-Firmware/tree/MK3_silent_mode_message

**Comment by arekm** [comment]
This depends on prusa firmware reporting only current mode
https://github.com/prusa3d/Prusa-Firmware/pull/2735 

With that plugin will just work and use correct mode.

(or manual plugin setting could be added but lets hope it gets improved in firmware).
