### ISSUE TITLE
Override completion percentage

### ISSUE THREAD

**Issue by hergtoler** [kanocz/octopi_eta_override#5]
Is it possible to have this (or another plugin) override the print completion percentage?  The Prusa LCD displays the M73 percentage, while Octoprint uses M27 to calculate a very rough approximation. 
 Certain models cause these two percentages to be VERY different.

I tried looking at it myself, but I couldn't find anything in the Octoprint API to allow it.  That certainly doesn't mean it's not there and I just overlooked it, though.

**Comment by kanocz** [comment]
just checked source of OctoPrint... can't find any easy way to implement this :( on the other hand (at least for me) remaining time is that important information...

**Comment by hergtoler** [comment]
Agreed.  Time/ETA is the important number. Thanks for looking at it and confirming I didn't miss something easy.
