### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by cp2004** [kanocz/octopi_eta_override#7]
As you are probably aware, OctoPrint currently supports Python 2 & 3 simultaneously. Users will begin migrating to Python 3 soon and your plugin will not be installable. As of March 2021, it will switch to Python 3 only.
Please see the guide [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html)

Having taken a look at your plugin, there is not too much Python so if you don't want to update it, I could PR to sort it out. Let me know what you think

**Comment by kanocz** [comment]
@cp2004 if you can create PR it could be great! because I know myself and will not found time until March 2021 when it will stop working for me :)

**Comment by cp2004** [comment]
I'll have a look later, watch out for a PR
