### ISSUE TITLE
 Support all printers with M73 command

### ISSUE THREAD

**Issue by adelyser** [kanocz/octopi_eta_override#9]
It would be better to process the M73 command as it's passed through instead of the specific Prusa response.  This would allow this plugin to work with all printers that support the M73 command, not just Prusa printers.

**Comment by kanocz** [comment]
@adelyser this plugin was created for supporting M73 while printing from sdcard, not from octoprint itself (I think it's just exist other plugin supporting M73 parsing while printing from octoprint)
